// Home Items
export const GET_HOME_ITEMS_LOADING = 'GET_HOME_ITEMS_LOADING';
export const GET_HOME_ITEMS_SUCCESS = 'GET_HOME_ITEMS_SUCCESS';
export const GET_HOME_ITEMS_ERROR = 'GET_HOME_ITEMS_ERROR';
export const CLEAR_HOME_ITEMS = 'CLEAR_HOME_ITEMS';
